# Site settings
title: SherryLearnsToCode
header-img: img/home-bg.png
email: sherryptk@gmail.com
copyright_name: sherryptk
description: > # this means to ignore newlines until "baseurl:"
  Ruby on Rails, JavaScript, React and more...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sherryptk
learn_profile: sherryptk
email_username: sherryptk@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
